# From https://github.com/CrunchyData/pg_tileserv/blob/master/examples/docker/docker-compose.yml
version: "3"

services:
  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    container_name: pg_tileserv
    environment:
      - DATABASE_URL=postgres://tileserv:tileserv@pg_tileserv_db/tileserv
    depends_on:
      - pg_tileserv_db
    ports:
      - 7800:7800

  pg_tileserv_db:
    image: postgis/postgis:13-3.0-alpine
    container_name: pg_tileserv_db
    volumes:
      - ./data:/work
      - pg_tileserv_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tileserv
      - POSTGRES_PASSWORD=tileserv
      - POSTGRES_DB=tileserv

  flask-frontend:
    image: flaskvectortiles_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskapp
    ports:
      - 8000:8000
    depends_on:
      - pg_tileserv
      - pg_tileserv_db

volumes:
  pg_tileserv_db: null
